/// A recipe generated by the AI from a list of leftover ingredients.
/// This is a plain model parsed from the AI's JSON response. It is only
/// persisted to the database when the user chooses to save it.
class AiRecipe {
  final String title;
  final String description;
  final int cookTime;
  final String difficulty;
  final int servings;
  final List<AiIngredient> ingredients;
  final List<AiStep> steps;

  AiRecipe({
    required this.title,
    required this.description,
    required this.cookTime,
    required this.difficulty,
    required this.servings,
    required this.ingredients,
    required this.steps,
  });

  factory AiRecipe.fromJson(Map<String, dynamic> json) {
    return AiRecipe(
      title: (json['title'] ?? 'Resep Tanpa Nama').toString(),
      description: (json['description'] ?? '').toString(),
      cookTime: _asInt(json['cookTime'], fallback: 30),
      difficulty: (json['difficulty'] ?? 'Sedang').toString(),
      servings: _asInt(json['servings'], fallback: 2),
      ingredients: (json['ingredients'] as List? ?? [])
          .whereType<Map<String, dynamic>>()
          .map(AiIngredient.fromJson)
          .toList(),
      steps: (json['steps'] as List? ?? [])
          .map((e) => e.toString())
          .where((e) => e.trim().isNotEmpty)
          .toList()
          .asMap()
          .entries
          .map((e) => AiStep(stepNumber: e.key + 1, instruction: e.value))
          .toList(),
    );
  }

  static int _asInt(dynamic value, {required int fallback}) {
    if (value is int) return value;
    if (value is double) return value.toInt();
    if (value is String) return int.tryParse(value) ?? fallback;
    return fallback;
  }
}

class AiIngredient {
  final String name;
  final double amount;
  final String unit;

  AiIngredient({required this.name, required this.amount, required this.unit});

  factory AiIngredient.fromJson(Map<String, dynamic> json) {
    return AiIngredient(
      name: (json['name'] ?? '').toString(),
      amount: _asDouble(json['amount']),
      unit: (json['unit'] ?? '').toString(),
    );
  }

  static double _asDouble(dynamic value) {
    if (value is num) return value.toDouble();
    if (value is String) return double.tryParse(value) ?? 1;
    return 1;
  }
}

class AiStep {
  final int stepNumber;
  final String instruction;

  AiStep({required this.stepNumber, required this.instruction});
}
